# CONFIGURACIÓN PRINCIPAL DEL PROYECTO
project:
  name: "BTC/USDT Trading System"
  base_currency: "USDT"
  risk_free_rate: 0.02  # Tasa libre de riesgo anual para cálculos (2%)

# CONFIGURACIÓN DE EXTRACCIÓN DE DATOS
data_fetcher:
  symbol: "BTCUSDT"
  interval: "1h"       # Opciones: 1m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  start_date: "2024-01-01"
  end_date: "2024-07-01"
  api:
    name: "bitunix"
    key: ""              # Tu API key (opcional para klines)
    secret: ""           # Tu API secret (cambio de secret_key a secret)
    base_url: "https://fapi.bitunix.com"
    endpoint: "/api/v1/futures/market/kline"
    max_retries: 3
    rate_limit: 10       # Máximo 10 req/sec según documentación oficial
    timeout: 30          # Timeout en segundos
  storage:
    raw_path: "data/raw"
    processed_path: "data/processed"
    file_format: "parquet"
    cache_enabled: true

# CONFIGURACIÓN DEL MOTOR DE FEATURES
feature_engine:
  indicators:
    - name: "rsi"
      normalize: true
      scaler: "minmax"  # Espesífico para RSI
      params:
        period: 14
    - name: "bollinger_bands"
      normalize: false
      params:
        period: 20
        std_dev: 2
    - name: "ema"
      normalize: true
      scaler: "standard"
      params:
        period: 12
    - name: "ema"
      normalize: true
      scaler: "standard"
      params:
        period: 26
    - name: "sma"
      normalize: true
      scaler: "standard"
      params:
        period: 20

# CONFIGURACIÓN DE LA ESTRATEGIA
strategy:
  name: "rsi_bollinger_strategy"
  parameters:
    rsi_oversold: 30
    rsi_overbought: 70
    bollinger_entry_threshold: 0.02

# CONFIGURACIÓN DEL BACKTESTING
backtest:
  initial_capital: 10000
  commission: 0.001
  start_date: "2024-01-01"
  end_date: "2024-07-01"
